// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcbXDIW8_nfHjypvHAVcLGclXMwzAZb0',
    appId: '1:317906777587:web:21304056cb2d4a99dd4e86',
    messagingSenderId: '317906777587',
    projectId: 'ojt-milan2024',
    authDomain: 'ojt-milan2024.firebaseapp.com',
    storageBucket: 'ojt-milan2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2zr8DEGrA6pbd8eGQp84mqYR0YcAafw',
    appId: '1:317906777587:android:fa20daf3ec19572add4e86',
    messagingSenderId: '317906777587',
    projectId: 'ojt-milan2024',
    storageBucket: 'ojt-milan2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7EU2Fi3A3fPbjY7bPz0_2CvDL1m6zW0',
    appId: '1:317906777587:ios:062efedadedfb14cdd4e86',
    messagingSenderId: '317906777587',
    projectId: 'ojt-milan2024',
    storageBucket: 'ojt-milan2024.firebasestorage.app',
    iosBundleId: 'com.example.flutterNestOjt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7EU2Fi3A3fPbjY7bPz0_2CvDL1m6zW0',
    appId: '1:317906777587:ios:062efedadedfb14cdd4e86',
    messagingSenderId: '317906777587',
    projectId: 'ojt-milan2024',
    storageBucket: 'ojt-milan2024.firebasestorage.app',
    iosBundleId: 'com.example.flutterNestOjt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVcbXDIW8_nfHjypvHAVcLGclXMwzAZb0',
    appId: '1:317906777587:web:375ed39d75f4c5cadd4e86',
    messagingSenderId: '317906777587',
    projectId: 'ojt-milan2024',
    authDomain: 'ojt-milan2024.firebaseapp.com',
    storageBucket: 'ojt-milan2024.firebasestorage.app',
  );
}
